# port
server:
  port: 25564
sa-token:
  ############## Sa-Token config (doc: https://sa-token.cc) ##############
  # token name(cookie name)
  token-name: satoken
  # token Validity period(seconds) Default: 30 days. -1 for permanent now: 300 days
  timeout: 25920000
  # 30 days, automatically re-active
  active-timeout: 2592000
  # login in different devices at the same time
  is-concurrent: true
  # login the same account in different devices with shared token
  is-share: true
  token-style=: uuid
  isPrint: false
  is-log: true
  jwt-secret-key: ohyzwymzyyqzdcj

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wordhub?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**
  profiles:
    active: secret

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.demo.wordhub.Mappers

urls:
  base: ${user.home}/WordHub
  avatar: ${urls.base}/avatars/